//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<TResult>
    {
        private class ChainElement
        {
            public global::System.Func<global::System.Boolean> Filter { get; private set; }
            public global::System.Func<TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::System.Func<global::System.Boolean> filter, global::System.Func<TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::System.Func<global::System.Boolean> filter, global::System.Func<TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke()
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter() ? el.Listener() : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<T, TResult>
    {
        private class ChainElement
        {
            public global::System.Func<T, global::System.Boolean> Filter { get; private set; }
            public global::System.Func<T, TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::System.Func<T, global::System.Boolean> filter, global::System.Func<T, TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::System.Func<T, global::System.Boolean> filter, global::System.Func<T, TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke(T arg0)
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter(arg0) ? el.Listener(arg0) : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<T1, T2, TResult>
    {
        private class ChainElement
        {
            public global::System.Func<T1, T2, global::System.Boolean> Filter { get; private set; }
            public global::System.Func<T1, T2, TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::System.Func<T1, T2, global::System.Boolean> filter, global::System.Func<T1, T2, TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::System.Func<T1, T2, global::System.Boolean> filter, global::System.Func<T1, T2, TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke(T1 arg0, T2 arg1)
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter(arg0, arg1) ? el.Listener(arg0, arg1) : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<T1, T2, T3, TResult>
    {
        private class ChainElement
        {
            public global::System.Func<T1, T2, T3, global::System.Boolean> Filter { get; private set; }
            public global::System.Func<T1, T2, T3, TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::System.Func<T1, T2, T3, global::System.Boolean> filter, global::System.Func<T1, T2, T3, TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::System.Func<T1, T2, T3, global::System.Boolean> filter, global::System.Func<T1, T2, T3, TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke(T1 arg0, T2 arg1, T3 arg2)
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter(arg0, arg1, arg2) ? el.Listener(arg0, arg1, arg2) : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<T1, T2, T3, T4, TResult>
    {
        private class ChainElement
        {
            public global::System.Func<T1, T2, T3, T4, global::System.Boolean> Filter { get; private set; }
            public global::System.Func<T1, T2, T3, T4, TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::System.Func<T1, T2, T3, T4, global::System.Boolean> filter, global::System.Func<T1, T2, T3, T4, TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::System.Func<T1, T2, T3, T4, global::System.Boolean> filter, global::System.Func<T1, T2, T3, T4, TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke(T1 arg0, T2 arg1, T3 arg2, T4 arg3)
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter(arg0, arg1, arg2, arg3) ? el.Listener(arg0, arg1, arg2, arg3) : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<T1, T2, T3, T4, T5, TResult>
    {
        private class ChainElement
        {
            public global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, global::System.Boolean> Filter { get; private set; }
            public global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, global::System.Boolean> filter, global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, global::System.Boolean> filter, global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke(T1 arg0, T2 arg1, T3 arg2, T4 arg3, T5 arg4)
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter(arg0, arg1, arg2, arg3, arg4) ? el.Listener(arg0, arg1, arg2, arg3, arg4) : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<T1, T2, T3, T4, T5, T6, TResult>
    {
        private class ChainElement
        {
            public global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, global::System.Boolean> Filter { get; private set; }
            public global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, global::System.Boolean> filter, global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, global::System.Boolean> filter, global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke(T1 arg0, T2 arg1, T3 arg2, T4 arg3, T5 arg4, T6 arg5)
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter(arg0, arg1, arg2, arg3, arg4, arg5) ? el.Listener(arg0, arg1, arg2, arg3, arg4, arg5) : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

namespace DataVault.Core.Helpers.Events
{
    public class AggregatingCallbackChain<T1, T2, T3, T4, T5, T6, T7, TResult>
    {
        private class ChainElement
        {
            public global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, T7, global::System.Boolean> Filter { get; private set; }
            public global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, T7, TResult> Listener { get; private set; }
            public global::System.Double Sequence { get; private set; }

            public ChainElement(global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, T7, global::System.Boolean> filter, global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, T7, TResult> listener, global::System.Double sequence)
            {
                Filter = filter;
                Listener = listener;
                Sequence = sequence;
            }
        }

        private class CallbackChainRegistration : global::System.IDisposable
        {
            private bool _isDisposed = false;
            private readonly global::System.Action _unregistrationLogic;

            public CallbackChainRegistration(global::System.Action unregistrationLogic)
            {
                _unregistrationLogic = unregistrationLogic;
            }

            public void Dispose()
            {
               if (!_isDisposed)
               {
                   _isDisposed = true;
                   _unregistrationLogic();
               }
            }
        }

        private readonly global::System.Collections.Generic.List<ChainElement> _chain = new global::System.Collections.Generic.List<ChainElement>();

        public global::System.IDisposable Add(global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, T7, global::System.Boolean> filter, global::DataVault.Core.Helpers.Func<T1, T2, T3, T4, T5, T6, T7, TResult> listener, global::System.Double sequence)
        {
            var element = new ChainElement(filter, listener, sequence);
            _chain.Add(element);
            _chain.Sort((el1, el2) => global::System.Collections.Generic.Comparer<global::System.Double>.Default.Compare(el1.Sequence, el2.Sequence));
            return new CallbackChainRegistration(() => _chain.Remove(element));
        }

        private readonly TResult _default;
        private readonly global::System.Func<TResult, TResult, TResult> _aggregator;

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator)
        {
            _aggregator = aggregator;
            _default = default(TResult);
        }

        public AggregatingCallbackChain(global::System.Func<TResult, TResult, TResult> aggregator, TResult @default)
        {
            _aggregator = aggregator;
            _default = @default;
        }

        public TResult Invoke(T1 arg0, T2 arg1, T3 arg2, T4 arg3, T5 arg4, T6 arg5, T7 arg6)
        {
            var results = global::System.Linq.Enumerable.Select(_chain, el => el.Filter(arg0, arg1, arg2, arg3, arg4, arg5, arg6) ? el.Listener(arg0, arg1, arg2, arg3, arg4, arg5, arg6) : _default);
            return global::System.Linq.Enumerable.Aggregate(results, _default, _aggregator);
        }
        
        public override global::System.String ToString()
        {
            var hierarchy = global::DataVault.Core.Helpers.Reflection.ReflectionHelper.LookupInheritanceChain(this.GetType());
            var veryThisType = global::System.Linq.Enumerable.ElementAt(global::System.Linq.Enumerable.Reverse(hierarchy), 1);
            var gargs = global::DataVault.Core.Helpers.Reflection.GenericsHelper.XGetGenericArguments(veryThisType);
            var payload = global::DataVault.Core.Helpers.EnumerableExtensions.SkipLast(gargs, 1);
            var returns = global::System.Linq.Enumerable.Last(gargs);
            
            var payloadTypes = global::System.Linq.Enumerable.Select(payload, t => global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(t));
            var payloadMacro = global::DataVault.Core.Helpers.EnumerableExtensions.StringJoin(payloadTypes);
            var returnsMacro = global::DataVault.Core.Helpers.ToStringHelper.GetUnqualifiedCSharpTypeName(returns);
            return global::System.String.Format("{{Listeners: {0}, payload schema: [{1}], type: returns {2}}}", _chain.Count, payloadMacro, returnsMacro);
        }
    }
}

