//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVault.Core.Helpers
{
    public static class Tuples
    {
        public static Tuple<T> New<T>(T f0)
        {
            return new Tuple<T>(f0);
        }

        public static Tuple<T1, T2> New<T1, T2>(T1 f0, T2 f1)
        {
            return new Tuple<T1, T2>(f0, f1);
        }

        public static Tuple<T1, T2, T3> New<T1, T2, T3>(T1 f0, T2 f1, T3 f2)
        {
            return new Tuple<T1, T2, T3>(f0, f1, f2);
        }

        public static Tuple<T1, T2, T3, T4> New<T1, T2, T3, T4>(T1 f0, T2 f1, T3 f2, T4 f3)
        {
            return new Tuple<T1, T2, T3, T4>(f0, f1, f2, f3);
        }

        public static Tuple<T1, T2, T3, T4, T5> New<T1, T2, T3, T4, T5>(T1 f0, T2 f1, T3 f2, T4 f3, T5 f4)
        {
            return new Tuple<T1, T2, T3, T4, T5>(f0, f1, f2, f3, f4);
        }

        public static Tuple<T1, T2, T3, T4, T5, T6> New<T1, T2, T3, T4, T5, T6>(T1 f0, T2 f1, T3 f2, T4 f3, T5 f4, T6 f5)
        {
            return new Tuple<T1, T2, T3, T4, T5, T6>(f0, f1, f2, f3, f4, f5);
        }

        public static Tuple<T1, T2, T3, T4, T5, T6, T7> New<T1, T2, T3, T4, T5, T6, T7>(T1 f0, T2 f1, T3 f2, T4 f3, T5 f4, T6 f5, T7 f6)
        {
            return new Tuple<T1, T2, T3, T4, T5, T6, T7>(f0, f1, f2, f3, f4, f5, f6);
        }

    }

    public class Tuple<T>
    {
        public T F0 { get; private set; }

        public Tuple(T f0)
        {
            F0 = f0;
        }
    }

    public class Tuple<T1, T2>
    {
        public T1 F0 { get; private set; }
        public T2 F1 { get; private set; }

        public Tuple(T1 f0, T2 f1)
        {
            F0 = f0;
            F1 = f1;
        }
    }

    public class Tuple<T1, T2, T3>
    {
        public T1 F0 { get; private set; }
        public T2 F1 { get; private set; }
        public T3 F2 { get; private set; }

        public Tuple(T1 f0, T2 f1, T3 f2)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
        }
    }

    public class Tuple<T1, T2, T3, T4>
    {
        public T1 F0 { get; private set; }
        public T2 F1 { get; private set; }
        public T3 F2 { get; private set; }
        public T4 F3 { get; private set; }

        public Tuple(T1 f0, T2 f1, T3 f2, T4 f3)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
        }
    }

    public class Tuple<T1, T2, T3, T4, T5>
    {
        public T1 F0 { get; private set; }
        public T2 F1 { get; private set; }
        public T3 F2 { get; private set; }
        public T4 F3 { get; private set; }
        public T5 F4 { get; private set; }

        public Tuple(T1 f0, T2 f1, T3 f2, T4 f3, T5 f4)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
        }
    }

    public class Tuple<T1, T2, T3, T4, T5, T6>
    {
        public T1 F0 { get; private set; }
        public T2 F1 { get; private set; }
        public T3 F2 { get; private set; }
        public T4 F3 { get; private set; }
        public T5 F4 { get; private set; }
        public T6 F5 { get; private set; }

        public Tuple(T1 f0, T2 f1, T3 f2, T4 f3, T5 f4, T6 f5)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
        }
    }

    public class Tuple<T1, T2, T3, T4, T5, T6, T7>
    {
        public T1 F0 { get; private set; }
        public T2 F1 { get; private set; }
        public T3 F2 { get; private set; }
        public T4 F3 { get; private set; }
        public T5 F4 { get; private set; }
        public T6 F5 { get; private set; }
        public T7 F6 { get; private set; }

        public Tuple(T1 f0, T2 f1, T3 f2, T4 f3, T5 f4, T6 f5, T7 f6)
        {
            F0 = f0;
            F1 = f1;
            F2 = f2;
            F3 = f3;
            F4 = f4;
            F5 = f5;
            F6 = f6;
        }
    }


}